services:
  traefik:
    image: docker.io/library/traefik:3.6
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 9090:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${STACKS_PATH}/traefik/config:/etc/traefik:ro
      - ${STACKS_PATH}/traefik/certs:/var/traefik/certs
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}  # <-- Change this to your Cloudflare API Token
    networks:
      static:
        ipv4_address: 172.7.7.5
      default: null
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
      # Base URL of your domain example.com
      - traefik.http.routers.traefik-secure.tls.domains[0].main=${TRAEFIK_BASEURL}
      - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${TRAEFIK_BASEURL}
      # Base URL of your subdomain if applicable sub.example.com
      - traefik.http.routers.traefik-secure.tls.domains[1].main=${TRAEFIK_BASEURL_SUB}
      - traefik.http.routers.traefik-secure.tls.domains[1].sans=*.${TRAEFIK_BASEURL_SUB}
networks:
  default:
    name: proxy
    external: true
  static:
    external: true
