services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - ${STACKS_PATH}/backrest/data:/data
      - ${STACKS_PATH}/backrest/config:/config
      - ${STACKS_PATH}/backrest/cache:/cache
      - ${STACKS_PATH}/backrest/tmp:/tmp
      - ${STACKS_PATH}/backrest/rclone:/root/.config/rclone  # Shared rclone config
      - ${BACKUP_PATH}:/backups
      - ${RESTORE_PATH}:/restore
      - ${STACKS_PATH}:/userdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Madrid
    ports:
      - 9898:9898
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.entrypoints=websecure
      - traefik.http.routers.backrest.rule=Host(`${BACKREST_HOST}`)
      - traefik.http.routers.backrest.tls=true

  rclone-gui:
    image: decovar/rclone-rc-web-gui:latest
    container_name: rclone-gui
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - RCLONE_ALLOW_ORIGIN_SCHEME=http
      - RCLONE_ALLOW_ORIGIN_HOST=127.0.0.1
      - RCLONE_ALLOW_ORIGIN_PORT=5572
      - RCLONE_USER=${RCLONE_USER}
      - RCLONE_PASS=${RCLONE_PW}
    ports:
      - 5572:5572
    volumes:
      - ${STACKS_PATH}/backrest/rclone:/config:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.rclone.entrypoints=websecure
      - traefik.http.routers.rclone.rule=Host(`${RCLONE_HOST}`)
      - traefik.http.routers.rclone.tls=true
      - traefik.http.services.rclone.loadbalancer.server.port=5572
    depends_on:
      - backrest

networks:
  default:
    external: true
    name: proxy