services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    # command: rclone rcd --rc-web-gui --rc-web-gui-no-open-browser
    volumes:
      - ${STACKS_PATH}/backrest/data:/data
      - ${STACKS_PATH}/backrest/config:/config
      - ${STACKS_PATH}/backrest/cache:/cache
      - ${STACKS_PATH}/backrest/tmp:/tmp
      - ${STACKS_PATH}/backrest/rclone:/root/.config/rclone  # Shared rclone config
      - ${BACKUP_PATH}:/backups
      - ${RESTORE_PATH}:/restore
      - ${STACKS_PATH}:/userdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Madrid
    ports:
      - 9898:9898 # backrest
      - 5572:5572 # rclone
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.entrypoints=websecure
      - traefik.http.routers.backrest.rule=Host(`${BACKREST_HOST}`)
      - traefik.http.routers.backrest.service=backrest
      - traefik.http.routers.backrest.tls=true
      - traefik.http.services.backrest.loadbalancer.server.port=9898
      - traefik.http.routers.rclone.entrypoints=websecure
      - traefik.http.routers.rclone.rule=Host(`${RCLONE_HOST}`)
      - traefik.http.routers.rclone.service=rclone
      - traefik.http.routers.rclone.tls=true
      - traefik.http.services.rclone.loadbalancer.server.port=5572

networks:
  default:
    external: true
    name: proxy