services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    command: rcd --rc-web-gui --rc-addr :5572
    volumes:
      - ${STACKS_PATH}/backrest/data:/data
      - ${STACKS_PATH}/backrest/config:/config
      - ${STACKS_PATH}/backrest/cache:/cache
      - ${STACKS_PATH}/backrest/tmp:/tmp
      - ${STACKS_PATH}/backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - ${BACKUP_PATH}:/backups
      - ${RESTORE_PATH}:/restore
      - ${STACKS_PATH}:/userdata  # Mount local paths to backup
      - /var/run/docker.sock:/var/run/docker.sock:ro # For starting/stopping containers
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Madrid
    ports:
      - 9898:9898
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.entrypoints=websecure
      - traefik.http.routers.backrest.rule=Host(`${BACKREST_HOST}`)
      - traefik.http.routers.backrest.tls=true
      - traefik.http.routers.rclone.entrypoints=websecure
      - traefik.http.routers.rclone.rule=Host(`${RCLONE_HOST}`)
      - traefik.http.routers.rclone.tls=true
      - traefik.http.services.rclone.loadbalancer.server.port=5572
networks:
  default:
    name: proxy
    external: true
