services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    command: rclone rcd --rc-web-gui
    volumes:
      - ${STACKS_PATH}/backrest/data:/data
      - ${STACKS_PATH}/backrest/config:/config
      - ${STACKS_PATH}/backrest/cache:/cache
      - ${STACKS_PATH}/backrest/tmp:/tmp
      - ${STACKS_PATH}/backrest/rclone:/root/.config/rclone  # Shared rclone config
      - ${BACKUP_PATH}:/backups
      - ${RESTORE_PATH}:/restore
      - ${STACKS_PATH}:/userdata
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Madrid
    ports:
      - 9898:9898
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backrest.entrypoints=websecure
      - traefik.http.routers.backrest.rule=Host(`${BACKREST_HOST}`)
      - traefik.http.routers.backrest.tls=true

networks:
  default:
    external: true
    name: proxy