services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STACKS_PATH}/homarr/appdata:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    ports:
      - '7575:7575'
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.entrypoints=websecure
      - traefik.http.routers.homarr.rule=Host(`${HOMARR_HOST}`)
      - traefik.http.routers.homarr.tls=true
      # Template labels for multi host/service Traefik deployment
      # - traefik.http.routers.homarralt.entrypoints=websecure
      # - traefik.http.routers.homarralt.rule=Host(`${HOMARR_HOST_ALT}`)
      # - traefik.http.routers.homarralt.tls=true
      # - traefik.http.routers.homarr.tls.certresolver=cloudflare
networks:
  default:
    name: proxy
    external: true