---
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    networks:
      static:
        ipv4_address: 172.7.7.7
      default: null
    volumes:
      - ${STACKS_PATH}/adguard/work:/opt/adguardhome/work
      - ${STACKS_PATH}/adguard/conf:/opt/adguardhome/conf
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 5002:5002/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entrypoints=websecure
      - traefik.http.routers.adguard.rule=Host(`${AG_HOST}`)
      - traefik.http.routers.adguard.tls=true
      - traefik.http.routers.adguard.service=adguard
      - traefik.http.services.adguard.loadbalancer.server.port=5002
      
networks:
  default:
    name: proxy
    external: true
  static:
    external: true
