services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    networks:
      # arrs_default:
      #   ipv4_address: 173.25.0.41
      default: null
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/jelly/jellyfin:/config
      - ${MEDIA_PATH}/tvshows:/data/tvshows
      - ${MEDIA_PATH}/movies:/data/movies
    ports:
      - 8096:8096
      - 7359:7359
      - 1900:1900
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jelly.${JELLY_HOST}`)
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/jelly/jellyseerr:/app/config    
    networks:
      default: null
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyseerr.entrypoints=websecure
      - traefik.http.routers.jellyseerr.rule=Host(`js.${JELLY_HOST}`)
      - traefik.http.routers.jellyseerr.tls=true
      - traefik.http.services.jellyseerr.loadbalancer.server.port=5055
networks:
  # arrs_default:
  #   external: true
  default:
    name: proxy
    external: true
